# Generated by Django 2.2.12 on 2020-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('typed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'linguagem',
                'verbose_name_plural': 'linguagens',
                'ordering': ('name',),
            },
        ),
    ]
